/* Generated By:JavaCC: Do not edit this line. ComidaConstants.java */
package controle;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ComidaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARROZ = 6;
  /** RegularExpression Id. */
  int FEIJAO = 7;
  /** RegularExpression Id. */
  int PAO = 8;
  /** RegularExpression Id. */
  int SALAME = 9;
  /** RegularExpression Id. */
  int PIMENTA = 10;
  /** RegularExpression Id. */
  int LINGUICA = 11;
  /** RegularExpression Id. */
  int BATATA_PALHA = 12;
  /** RegularExpression Id. */
  int BATATA_RUSTICA = 13;
  /** RegularExpression Id. */
  int TA_NA_MESA = 14;
  /** RegularExpression Id. */
  int ENTER = 15;
  /** RegularExpression Id. */
  int ABRE_PARENTESES = 16;
  /** RegularExpression Id. */
  int FECHA_PARENTESES = 17;
  /** RegularExpression Id. */
  int ABRE_CHAVE = 18;
  /** RegularExpression Id. */
  int FECHA_CHAVE = 19;
  /** RegularExpression Id. */
  int VIRGULA = 20;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 21;
  /** RegularExpression Id. */
  int DELIMITAR_TEXTO = 22;
  /** RegularExpression Id. */
  int SETA = 23;
  /** RegularExpression Id. */
  int PLUS = 24;
  /** RegularExpression Id. */
  int MINUS = 25;
  /** RegularExpression Id. */
  int MULTIPLY = 26;
  /** RegularExpression Id. */
  int DIVIDE = 27;
  /** RegularExpression Id. */
  int EXP = 28;
  /** RegularExpression Id. */
  int CONCAT = 29;
  /** RegularExpression Id. */
  int FALSO = 30;
  /** RegularExpression Id. */
  int VERDADEIRO = 31;
  /** RegularExpression Id. */
  int MAIOR = 32;
  /** RegularExpression Id. */
  int MENOR = 33;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 34;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 35;
  /** RegularExpression Id. */
  int IGUAL = 36;
  /** RegularExpression Id. */
  int DIFERENTE = 37;
  /** RegularExpression Id. */
  int ATRIBUIR = 38;
  /** RegularExpression Id. */
  int LETRA_MAIUSCULA = 39;
  /** RegularExpression Id. */
  int LETRA_MINUSCULA = 40;
  /** RegularExpression Id. */
  int NUMERO = 41;
  /** RegularExpression Id. */
  int DIGITO = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 4>",
    "<token of kind 5>",
    "\"arroz\"",
    "\"feijao\"",
    "\"pao\"",
    "\"salame\"",
    "\"pimenta\"",
    "\"linguica\"",
    "\"batata_palha\"",
    "\"batata_rustica\"",
    "\"ta_na_mesa\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\"\\\'\"",
    "\"->\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"++\"",
    "\"falso\"",
    "\"verdadeiro\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"=\"",
    "<LETRA_MAIUSCULA>",
    "<LETRA_MINUSCULA>",
    "<NUMERO>",
    "<DIGITO>",
    "\"_\"",
    "\"\"",
    "\"grelha:\"",
    "\"churrasqueira\"",
  };

}
