/* Generated By:JavaCC: Do not edit this line. ComidaConstants.java */
package controle;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ComidaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARROZ = 5;
  /** RegularExpression Id. */
  int FEIJAO = 6;
  /** RegularExpression Id. */
  int PAO = 7;
  /** RegularExpression Id. */
  int SALAME = 8;
  /** RegularExpression Id. */
  int PIMENTA = 9;
  /** RegularExpression Id. */
  int LINGUICA = 10;
  /** RegularExpression Id. */
  int BATATA_PALHA = 11;
  /** RegularExpression Id. */
  int BATATA_RUSTICA = 12;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int MINUS = 14;
  /** RegularExpression Id. */
  int MULTIPLY = 15;
  /** RegularExpression Id. */
  int DIVIDE = 16;
  /** RegularExpression Id. */
  int EXP = 17;
  /** RegularExpression Id. */
  int CONCAT = 18;
  /** RegularExpression Id. */
  int ID = 19;
  /** RegularExpression Id. */
  int FALSO = 20;
  /** RegularExpression Id. */
  int VERDADEIRO = 21;
  /** RegularExpression Id. */
  int CONSTANT = 22;
  /** RegularExpression Id. */
  int DIGIT = 23;
  /** RegularExpression Id. */
  int TA_NA_MESA = 24;
  /** RegularExpression Id. */
  int STRING_LITERAL = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"arroz\"",
    "\"feijao\"",
    "\"pao\"",
    "\"salame\"",
    "\"pimenta\"",
    "\"linguica\"",
    "\"batata_palha\"",
    "\"batata_rustica\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"\\\\+\"",
    "<ID>",
    "\"falso\"",
    "\"verdadeiro\"",
    "<CONSTANT>",
    "<DIGIT>",
    "\"ta_na_mesa\"",
    "<STRING_LITERAL>",
    "\"{\"",
    "\"}\"",
    "\"\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"grelha:\"",
    "\"->\"",
    "\"churrasqueira\"",
  };

}
