/* Generated By:JavaCC: Do not edit this line. ComidaConstants.java */
package controle;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ComidaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARROZ = 6;
  /** RegularExpression Id. */
  int FEIJAO = 7;
  /** RegularExpression Id. */
  int PAO = 8;
  /** RegularExpression Id. */
  int SALAME = 9;
  /** RegularExpression Id. */
  int PIMENTA = 10;
  /** RegularExpression Id. */
  int LINGUICA = 11;
  /** RegularExpression Id. */
  int BATATA_PALHA = 12;
  /** RegularExpression Id. */
  int BATATA_RUSTICA = 13;
  /** RegularExpression Id. */
  int TA_NA_MESA = 14;
  /** RegularExpression Id. */
  int ENTER = 15;
  /** RegularExpression Id. */
  int GRELHA = 16;
  /** RegularExpression Id. */
  int CHURRASQUEIRA = 17;
  /** RegularExpression Id. */
  int DOIS_PONTOS = 18;
  /** RegularExpression Id. */
  int UNDERLINE = 19;
  /** RegularExpression Id. */
  int ABRE_PARENTESES = 20;
  /** RegularExpression Id. */
  int FECHA_PARENTESES = 21;
  /** RegularExpression Id. */
  int ABRE_CHAVE = 22;
  /** RegularExpression Id. */
  int FECHA_CHAVE = 23;
  /** RegularExpression Id. */
  int VIRGULA = 24;
  /** RegularExpression Id. */
  int PONTO_VIRGULA = 25;
  /** RegularExpression Id. */
  int DELIMITAR_TEXTO = 26;
  /** RegularExpression Id. */
  int SETA = 27;
  /** RegularExpression Id. */
  int PLUS = 28;
  /** RegularExpression Id. */
  int MINUS = 29;
  /** RegularExpression Id. */
  int MULTIPLY = 30;
  /** RegularExpression Id. */
  int DIVIDE = 31;
  /** RegularExpression Id. */
  int EXP = 32;
  /** RegularExpression Id. */
  int FALSO = 33;
  /** RegularExpression Id. */
  int VERDADEIRO = 34;
  /** RegularExpression Id. */
  int MAIOR = 35;
  /** RegularExpression Id. */
  int MENOR = 36;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 37;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 38;
  /** RegularExpression Id. */
  int IGUAL = 39;
  /** RegularExpression Id. */
  int DIFERENTE = 40;
  /** RegularExpression Id. */
  int IGUAL_LOGICO = 41;
  /** RegularExpression Id. */
  int LETRA_MAIUSCULA = 42;
  /** RegularExpression Id. */
  int LETRA_MINUSCULA = 43;
  /** RegularExpression Id. */
  int CARACTERE_ESPECIAL = 44;
  /** RegularExpression Id. */
  int PONTO = 45;
  /** RegularExpression Id. */
  int DIGITO = 46;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 4>",
    "<token of kind 5>",
    "\"arroz\"",
    "\"feij\\u00e3o\"",
    "\"p\\u00e3o\"",
    "\"salame\"",
    "\"pimenta\"",
    "\"lingui\\u00e7a\"",
    "\"batata_palha\"",
    "\"batata_rustica\"",
    "\"ta_na_mesa\"",
    "\"\\n\"",
    "\"grelha\"",
    "\"churrasqueira\"",
    "\":\"",
    "\"_\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\"\\\'\"",
    "\"->\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"ruim\"",
    "\"bom\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"!=\"",
    "\"==\"",
    "<LETRA_MAIUSCULA>",
    "<LETRA_MINUSCULA>",
    "<CARACTERE_ESPECIAL>",
    "<PONTO>",
    "<DIGITO>",
  };

}
